### ISSUE TITLE
Add a high-quality face/body tracking API to discourage poor/discriminatory implementations

### ISSUE THREAD

**Issue by steely-glint** [w3c/mediacapture-transform#1]
Two of the usecases for this (excellent) API depend on face and/or body tracking. 
(Funny hats and Background removal)
It has been seen that many of these algorithms have been trained on inadequate datasets and perform badly for certain groups of users.
This API must offer high quality implementations of face and body tracking so that this problem can be avoided before it happens. 
The site developer can use/load their own implementations of course, but the presence of a high quality implemenation will raise the bar and discourage substitution with worse methods.

**Comment by alvestrand** [comment]
I'm not sure about this. It would seem like a separable concern, and I tend to be very supportive of concern separation.
If one were to specify such an API that is defined in terms of a stream of VideoFrame, that would offer instant pluggability without any spec linkage needed (and a native implementation could save some memory copies by operating on the internal representation and only surface the actual tracking result).

But this may be out of webrtc scope - is anything like this being pursued in (for instance) the AR/XR groups?

**Comment by steely-glint** [comment]
I don't beleive it is separable. This proposed API claims to enable Funny Hats. If delivered without a non-discriminatory face tracking implementation it will cause lazy/discriminatory sites to proliferate.

Have a listen to the first 5 mins of a recent podcast I co-host  https://distributedfutu.re/#episode56 for a sense of the scale of the problem that already exists: 'not working for darker skin tones .... Has become the norm now for me' says my co-host.

**Comment by alvestrand** [comment]
@steely-glint I have added this to the agenda for Wednesday Dec 2's WG meeting. I'd like to get a firm grasp of "next steps".

**Comment by guidou** [comment]
Closing, since my understanding is that we have decided to work on this and other potential platform transformations in a separate document (maybe mediacapture-extensions initially).
