### ISSUE TITLE
First timestamp generated by mediastream fails

### ISSUE THREAD

**Issue by tiuvi** [w3c/mediacapture-transform#111]
I have seen several problems about this, some from two years ago, what would be the steps to follow to use MediaStreamTrackProcessor with getusermedia.
Since the first timestamp is wrong and also does not return duration.
Sometimes it has given me a longer duration. I don't know if this depends on some factor that I don't know about.
Having a frame duration I can now calculate the timestamp and square it with the audio.

![image](https://github.com/w3c/mediacapture-transform/assets/69035383/876c6a55-3711-4337-a6b4-7ca8dc0e7d27)

This runs on my PC, it may be down, try the next day.
Demo: https://tiuvi.com/videoEditorWebCodecs

Currently I run getUserMedia recording, I encode them directly from the frames, another way is to save the audiodata in an array and the frames on disk, and another way is to save both audiodata and frames on disk, then I recreate the audiodata and videoframe objects again.

For this I need to have coherent times. Do you have a solution?

**Comment by guidou** [comment]
What do you mean by incorrect timestamps? Either way, it looks more like an implementation issue, so probably better to file a browser bug (crbug com for Chromium)

**Comment by tiuvi** [comment]
first video frame
![image](https://github.com/w3c/mediacapture-transform/assets/69035383/6bfbf8e6-356a-4f7c-8fc7-697519358324)

second video frame
![image](https://github.com/w3c/mediacapture-transform/assets/69035383/7e04394f-33c4-41a1-b02e-a6f6504591c4)
diference 10301311465 - 1384010  = 10299927455

**Comment by guidou** [comment]
Looks like an implementation bug, not a spec bug. Please file a browser bug with repro steps and any details that could help solve it.
