### ISSUE TITLE
Should MediaStreamTrackGenerator have an API to fine-tune MediaStreamTrack internal states?

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-transform#26]
A MediaStreamTrack might be muted/unmuted which will trigger events.
It is unclear how MediaStreamTrackGenerator allows surfacing such API.
This might be important in the case MediaStreamTrackGenerator is doing some processing on a track and wants to mirror the state of the track. For instance, if the origin track gets muted, the transformed track might want to also enter muted state.
Ditto for applyConstraints and so on.

**Comment by guidou** [comment]
I agree that the muted state should be controllable.
For hardware sources such as microphones, the muted state can be changed via a hardware button, for example.
For a programatically defined one like MSTG, we should have a programatic way to control the mute state.

**Comment by alvestrand** [comment]
A setMuted method was suggested in #55, but needs to be rewritten to be on VideoTrackGenerator.
Seems viable and reasonable to expose.

**Comment by alvestrand** [comment]
The VideoTrackGenerator (as adopted) has a "muted" attribute that fulfils this function.
Closing this issue as "fixed"; if more state needs to be manipulated, we can open more issues.
