### ISSUE TITLE
Call the streams algorithms

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-transform#36]
The streams spec has a [Using streams in other specifications](https://streams.spec.whatwg.org/#other-specs) section with algorithms we're meant to call. But we don't appear to be calling them. We should do that.

We seem light on algorithms to describe the fundamentals someone would need to get right to implement this web compatibly: threading model, timing, type checking, and error handling, which I'm unable to glean from current prose.

Since media capture typically happens on a media thread — out of process even — I'd expect a lot of "in parallel" and queued tasks to communicate from/to the JS thread.

A potential template to look at that might help is https://github.com/w3c/webrtc-insertable-streams/pull/51#discussion_r567910473. Similar to that patch, once we start calling the streams algorithms directly, this should unfurl how to answer these questions.

**Comment by guidou** [comment]
The spec is currently written in terms of results produced by the API, and not in terms of the steps needed to get those results.
However, since the streams spec recommends using those algorithms I'll prepare a PR to use them.
Semantics will not change, though.

**Comment by guidou** [comment]
The PRs to make use of these algorithms have landed, so closing this.
