### ISSUE TITLE
What does sink mean?

### ISSUE THREAD

**Issue by krave1986** [w3c/mediacapture-transform#39]
I am lead to this repo from this article:
https://web.dev/mediastreamtrack-insertable-media-processing/

Word "sink" is mentioned mutiple times in the doc.
What does sink mean here?
Could you please give some examples?

**Comment by dontcallmedom** [comment]
see https://w3c.github.io/mediacapture-main/getusermedia.html#the-model-sources-sinks-constraints-and-settings
