### ISSUE TITLE
Compare callback-based and ReadableStream-based exposure of video MediaStreamTrack media flow

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-transform#69]
MediaStreamTrack is encapsulating a flow of video frames and some applications might want to be notified when a new video frame happens:
- Existing applications would like to paint into a canvas for every track frame.
- Future applications might want to manipulate raw video frames (MediaStreamTrackProcessor use cases).

It would be interesting to evaluate the pros and cons of a callback-based approach vs. a ReadableStream-based approach.

**Comment by alvestrand** [comment]
Closing issue with the assumption that solutions in the WHATWG Streams space will solve these problems with no further modifications to the mediacapture-transform spec.
